-- Opcional: espelho em Supabase (o dashboard usa data/usuarios.json por padrão).
create table if not exists public.fidc_usuarios (
  id bigint generated by default as identity primary key,
  nome text not null,
  username text not null unique,
  senha_hash text not null,
  salt text not null,
  perfil text not null default 'usuario' check (perfil in ('admin', 'usuario')),
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);
